<script setup>
import { ref, computed, onMounted } from 'vue'
import { useDiagnosisStore } from './DiagnosisStore'
import { useRouter } from 'vue-router'
import jsPDF from 'jspdf'
import axios from 'axios'

const doctor = ref(null)
const token = localStorage.getItem('token')
const decoded = token ? JSON.parse(atob(token.split('.')[1])) : {}
const doctorId = decoded?.id

onMounted(async () => {
  if (doctorId && decoded.role === 'doctor') {
    try {
      const { data } = await axios.get(`/api/doctors/${doctorId}`, {
        headers: { Authorization: `Bearer ${token}` }
      })
      doctor.value = data
    } catch (err) {
      console.error('Failed to load doctor for PDF:', err)
    }
  }
})


const store = useDiagnosisStore()
const router = useRouter()

const needsFollowUp = ref(false)
const followUpDate = ref('')
const followUpNotes = ref('')

const showPdfModal = ref(false)
const pdfDataUrl = ref('')

const completeDiagnosis = async () => {
  if (needsFollowUp.value) {
    store.diagnosis.followUp = {
      date: followUpDate.value,
      notes: followUpNotes.value
    }
  }

  try {
    await store.completeDiagnosis() 
    generatePrescriptionPdfPreview() 
  } catch (err) {
    alert('Error completing diagnosis. Please try again.')
    console.error(err)
  }
}

const generatePrescriptionPdfPreview = () => {
  const doc = new jsPDF()
  let y = 30

  doc.setFillColor(34, 45, 65)
  doc.rect(0, 0, 210, 20, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text('Prescription', 105, 14, { align: 'center' })

  const d = doctor.value || {}
  doc.setFontSize(13)
  doc.setTextColor(33, 37, 41)
  doc.setFont('helvetica', 'bold')
  doc.text(`Dr ${d.firstName ?? ''} ${d.lastName ?? ''}`, 20, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  y += 7
  doc.text(`${d.specialization ?? ''}`, 20, y)
  y += 6
  doc.text(`Phone: ${d.phone ?? ''}`, 20, y)
  y += 6
  doc.text(`Email: ${d.email ?? ''}`, 20, y)
  y += 6
  doc.text(`Address: ${d.address ?? ''}`, 20, y)

  y = 30
  doc.setFontSize(11)
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 140, y)

  y = 80
  doc.setDrawColor(33, 150, 243)
  doc.setLineWidth(0.6)
  doc.line(20, y, 190, y)
  y += 10

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(33, 150, 243)
  doc.text('Medications', 20, y)
  y += 8
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(40, 40, 40)

  let meds = []
  try {
    meds = Array.isArray(store.diagnosis.prescription)
      ? store.diagnosis.prescription
      : JSON.parse(store.diagnosis.prescription)
  } catch {}

  meds.forEach(m => {
    doc.text(`• ${m.name} (${m.dose || 'n/a'})`, 25, y)
    y += 7
  })

  y += 15
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(11)
  doc.text('Signature: ______________________', 20, y)

  doc.setFontSize(9)
  doc.setTextColor(130, 130, 130)
  doc.text('Generated by BVGCare', 105, 290, { align: 'center' })

  const blob = doc.output('blob')
  const url = URL.createObjectURL(blob)
  pdfDataUrl.value = url
  showPdfModal.value = true
}

const downloadPrescriptionPdf = () => {
  const link = document.createElement('a')
  link.href = pdfDataUrl.value
  link.download = 'Prescription.pdf'
  link.click()
}

const closePdfModal = () => {
  showPdfModal.value = false
  pdfDataUrl.value = ''
  router.push('/dashboard') 
}


const prevStep = () => store.prevStep()
const saveDraft = () => store.saveDraft()
</script>

<template>
  <div class="diagnosis-step">
    <h3>Treatment Plan</h3>

    <div class="plan-section">
      <h4>Plan Details</h4>
      <textarea
        v-model="store.diagnosis.plan"
        class="plan-textarea"
        placeholder="Outline the treatment plan, follow-up instructions, and any referrals needed"
      ></textarea>

      <div class="plan-options">
        <label class="plan-option">
          <input type="checkbox" v-model="needsFollowUp" />
          <span>Schedule Follow-up</span>
        </label>

        <div v-if="needsFollowUp" class="followup-details">
          <label>Follow-up Date</label>
          <input type="date" v-model="followUpDate" class="input" />

          <label>Follow-up Notes</label>
          <input v-model="followUpNotes" placeholder="Reason for follow-up" class="input" />
        </div>
      </div>
    </div>

    <div class="step-actions">
      <div class="left-actions">
        <button class="btn-outline" @click="prevStep">← Back</button>
        <button class="btn-outline" @click="saveDraft">Save Draft</button>
      </div>
      <button class="btn-primary" @click="completeDiagnosis">Complete Diagnosis</button>
    </div>

    <!-- PDF Modal Preview -->
    <div v-if="showPdfModal" class="modal is-active">
      <div class="modal-background" @click="closePdfModal"></div>
      <div class="modal-content" style="background: white; padding: 2rem; border-radius: 8px;">
        <iframe :src="pdfDataUrl" width="100%" height="500px" style="border: none;"></iframe>
        <div style="margin-top: 1rem; text-align: right;">
          <button class="button is-info" @click="downloadPrescriptionPdf">Download PDF</button>
          <button class="button is-light ml-2" @click="closePdfModal">Close</button>
        </div>
      </div>
      <button class="modal-close is-large" @click="closePdfModal"></button>
    </div>
  </div>
</template>


<style scoped>
.plan-section {
  margin: 1.5rem 0;
}

.plan-textarea {
  width: 100%;
  min-height: 200px;
  padding: 1rem;
  border: 1px solid #ddd;
  border-radius: 6px;
  margin-bottom: 1.5rem;
}

.plan-options {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.plan-option {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  cursor: pointer;
}

.followup-details {
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 0.8rem;
  align-items: center;
  margin-top: 1rem;
  padding: 1rem;
  background: #f5f7fa;
  border-radius: 8px;
}

.step-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 2rem;
  flex-wrap: wrap;
  gap: 1rem;
}

.left-actions {
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
}

.btn-outline,
.btn-primary {
  padding: 0.6rem 1.2rem;
  font-size: 1rem;
  border-radius: 6px;
  cursor: pointer;
  transition: background-color 0.2s ease;
}

.btn-outline {
  background-color: white;
  border: 1px solid #ccc;
  color: #333;
}

.btn-outline:hover {
  background-color: #f0f0f0;
}

.btn-primary {
  background-color: #3273dc;
  border: none;
  color: white;
}

.btn-primary:disabled {
  background-color: #a1c5f2;
  cursor: not-allowed;
}

</style>